# Generated by Django 3.0.4 on 2020-03-16 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publication_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 16, 13, 54, 0, 223857, tzinfo=utc)),
        ),
    ]
