# Generated by Django 3.0.4 on 2020-03-16 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200316_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 13, 56, 39, 964121, tzinfo=utc)),
        ),
    ]
