# Generated by Django 3.0.4 on 2020-03-16 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200316_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
